In [19]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torchvision import transforms, datasets
from torch.utils.data import DataLoader

In [ ]:
class LeNet5(nn.Module):
    def __init__(self):
        super(LeNet5, self).__init__()

        self.conv1 = nn.Conv2d(1, 6, kernel_size=5, stride=1, padding=2)
        self.pool1 = nn.AvgPool2d(kernel_size=2, stride=2)
        self.conv2 = nn.Conv2d(6, 16, kernel_size=5)
        self.pool2 = nn.AvgPool2d(kernel_size=2, stride=2)
        self.conv3 = nn.Conv2d(16, 120, kernel_size=5)

        self.fc1 = nn.Linear(120, 84)
        self.fc2 = nn.Linear(84, 10)

    def forward(self, x):
        x = torch.tanh(self.conv1(x))
        x = self.pool1(x)
        x = torch.tanh(self.conv2(x))
        x = self.pool2(x)
        x = torch.tanh(self.conv3(x))
        x = x.view(x.size(0), -1)
        x = torch.tanh(self.fc1(x))
        x = self.fc2(x)
        return x

In [20]:
transforms = transforms.Compose([transforms.ToTensor()])

In [33]:
train_dataset = datasets.MNIST(
    root="data", train=True, download=False, transform=transforms
)
test_dataset = datasets.MNIST(
    root="data", train=False, download=False, transform=transforms
)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=1000, shuffle=False)

In [34]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [35]:
model = LeNet5().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [36]:
def train(model, loader, optimizer, criterion, epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()

        if batch_idx % 100 == 0:
            print(
                f"Train Epoch: {epoch} [{batch_idx * len(data)}/{len(loader.dataset)}]  Loss: {loss.item():.4f}'"
            )

In [37]:
def test(model, loader):
    model.eval()
    correct = 0
    total = 0
    loss_total = 0

    with torch.no_grad():
        for data, target in loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            loss = criterion(output, target)
            loss_total += loss.item()
            pred = output.argmax(dim=1)
            correct += pred.eq(target).sum().item()
            total += target.size(0)
    accuracy = 100 * correct / total

    print(
        f"\nTest set: Average loss: {loss_total / len(loader):.4f}, Accuracy: {correct}/{total} ({accuracy:.2f}%)\n"
    )

In [38]:
for epoch in range(1, 6):
    train(model, train_loader, optimizer, criterion, epoch)
    test(model, test_loader)

Train Epoch: 1 [0/60000]  Loss: 2.3146'
Train Epoch: 1 [6400/60000]  Loss: 0.3925'
Train Epoch: 1 [12800/60000]  Loss: 0.1681'
Train Epoch: 1 [19200/60000]  Loss: 0.2605'
Train Epoch: 1 [25600/60000]  Loss: 0.1034'
Train Epoch: 1 [32000/60000]  Loss: 0.1268'
Train Epoch: 1 [38400/60000]  Loss: 0.2403'
Train Epoch: 1 [44800/60000]  Loss: 0.1446'
Train Epoch: 1 [51200/60000]  Loss: 0.2352'
Train Epoch: 1 [57600/60000]  Loss: 0.0561'

Test set: Average loss: 0.1137, Accuracy: 9664/10000 (96.64%)

Train Epoch: 2 [0/60000]  Loss: 0.1448'
Train Epoch: 2 [6400/60000]  Loss: 0.1439'
Train Epoch: 2 [12800/60000]  Loss: 0.0761'
Train Epoch: 2 [19200/60000]  Loss: 0.0549'
Train Epoch: 2 [25600/60000]  Loss: 0.0461'
Train Epoch: 2 [32000/60000]  Loss: 0.0968'
Train Epoch: 2 [38400/60000]  Loss: 0.0147'
Train Epoch: 2 [44800/60000]  Loss: 0.0924'
Train Epoch: 2 [51200/60000]  Loss: 0.1209'
Train Epoch: 2 [57600/60000]  Loss: 0.0324'

Test set: Average loss: 0.0691, Accuracy: 9769/10000 (97.69%)

Tr

In [4]:
import numpy as np

np.eye(5)[[0, 1, 2, 3, 4]]

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
import numpy as np

np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
ali = [
    [1, 5, 6, 4, 8],
    [4, 50, 3, 8, 7],
    [8, 5, 7, 4, 6],
    [5, 8, 4, 6, 50],
    [5, 8, 7, 3, 6],
]
ali = np.array(ali)
input_data = np.pad(
    ali,
    ((2, 2), (2, 2)),
    mode="constant",
)
input_data

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  5,  6,  4,  8,  0,  0],
       [ 0,  0,  4, 50,  3,  8,  7,  0,  0],
       [ 0,  0,  8,  5,  7,  4,  6,  0,  0],
       [ 0,  0,  5,  8,  4,  6, 50,  0,  0],
       [ 0,  0,  5,  8,  7,  3,  6,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [125]:
a = np.random.rand(8, 3)
a

array([[0.26893591, 0.43317502, 0.24489025],
       [0.91335232, 0.32527073, 0.21255412],
       [0.5421353 , 0.88998036, 0.60753343],
       [0.60526387, 0.58623704, 0.60068163],
       [0.55316899, 0.70345836, 0.69884117],
       [0.77744044, 0.22255925, 0.63761264],
       [0.08826618, 0.26424135, 0.98133608],
       [0.15872941, 0.58845439, 0.96665832]])

In [126]:
b = np.ones((1, 3))
b

array([[1., 1., 1.]])

In [135]:
input_ = [1, 2, 3, 7, 9, 5, 1, 2]

In [136]:
c = np.dot(input_, a) + b
c

array([[18.2303417 , 17.74238849, 20.08965664]])

In [131]:
# ali = [[2, 5], [8, 9]]
ali = np.expand_dims(ali, 0)
ali.shape

(1, 1, 2, 2)

In [132]:
tav = ali.reshape(ali.shape[0], -1)
tav

array([[2, 5, 8, 9]])